### PR TITLE
Climsoft station api

### PR DESCRIPTION
**Pull request by faysal-ishtiaq**
Merge conflicts are resolved. But the tests are not working yet.

### CODE REVIEW

**Comment by isedwards** [comment]
@faysal-ishtiaq could you give a quick updates on which Climsoft tables are now supported and which ones remain?

We can either prioritse the order for implementing the final tables --- or, if all of the main tables that we need are already supported then we may move on to a couple of other issues first.

**Comment by faysal-ishtiaq** [comment]
@isedwards 

The following climsoft tables have CRUD:
  - acquisitiontype 
  - data_forms
  - flags
  - obselement
  - paperarchivedefinition
  - qcstatusdefinition
  - qctype
  - regkeys
  - station
  - synopfeature
  - featuregeographicalposition
  - instrument
  - observationfinal
  - observationinitial
  - obsscheduleclass
  - stationelement

There are only a few remaining tables. They will be done by tonight.

**Comment by faysal-ishtiaq** [comment]
@isedwards 

just finished till integration tests for all models. starting snapshot tests

**Comment by faysal-ishtiaq** [comment]
@isedwards 

just gone through the target tables from test db in `opencdms-test-data` repository. Now adding more information on read me.

**Comment by faysal-ishtiaq** [comment]
@isedwards 

I have just fixed mch db issue. Here is a demo request and response using curl:

```bash
04:34:40 faysal@pop-os ~ → curl -X 'GET' \
>   'http://localhost:8000/mch/API/stations' \
>   -H 'accept: application/json' \
>   -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdHJpbmciLCJleHAiOjE2Mzg2MTQwMzYsInRva2VuX3R5cGUiOiJhY2Nlc3MiLCJqdGkiOiJhZmM5YzU0MzI5NDY0MDA5OWM0ZGVlM2IzNzk1OTFhZSIsInVzZXJfaWQiOjF9.PDk23tWTzUTK-FOsNgcVhZcG9vybp1te1JGsoyg2zRc'


response:

[]

```

**Pull request merged**
